# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QNAIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QNAIDemo

  pod 'YYCategories'
	pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'SocketRocket','0.6.0'
#  pod 'QNRTCKit','3.1.2'
  pod 'IQKeyboardManager'
  pod 'Masonry'

  target 'QNAIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QNAIDemoUITests' do
    # Pods for testing
  end

end
